# Generated by Django 2.0 on 2020-07-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personage',
            name='paranters',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='合伙人'),
        ),
    ]
